### ISSUE TITLE
Where is the dataset from?

### ISSUE THREAD

**Issue by sourface94** [rohilshah95/Twitter-Personalities#3]
Hi where is this data set you used from and what is it called? Thanks

**Comment by Najq** [comment]
We generated our own dataset using the Twitter streaming API. All the tweets that contained their MBTI type were used for training.

**Comment by sourface94** [comment]
Thanks, so you found tweets where people said what their mbti type is within the tweet? 
If that's true did you cut the part where they say what their mbti is out of the tweet, because I cant see that in all of the tweets in the dataset.

**Comment by Najq** [comment]
Yes! That formed the training label, so we did cut it from the training data
